frame_rate: 50
use_depth_image: true
use_robot_base: false
arm_steps_length: [0.01, 0.01, 0.01, 0.01, 0.01, 0.01, 0.01]
cameras:
  left:
    rgb_topic: "/camera/leftview/color/image_raw"
    depth_topic: "/camera/leftview/aligned_depth_to_color/image_raw"
  right:
    rgb_topic: "/camera/rightview/color/image_rect_raw"
    depth_topic: "/camera/rightview/aligned_depth_to_color/image_raw"
  agent:
    rgb_topic: "/camera/agentview/color/image_raw"
    depth_topic: "/camera/agentview/aligned_depth_to_color/image_raw"
arms:
  puppet_left:
    recv_joint_state_topic: "/left/joint_states"
    recv_eef_pose_topic: "/left/eef_pose"
    send_joint_cmd_topic: "/left/joint_targets"
  puppet_right:
    recv_joint_state_topic: "/right/joint_states"
    recv_eef_pose_topic: "/right/eef_pose"
    send_joint_cmd_topic: "/right/joint_targets"
  master_left:
    recv_joint_state_topic: "/left/joint_targets"
  master_right:
    recv_joint_state_topic: "/right/joint_targets"
# robot_base:
#   recv_topic: "/base/odom"
#   send_topic: "/base/cmd_vel"
# ctrl_topic: "/robot_ctrl"